<?php
declare(strict_types=1);

// JellyBellyWiki SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

JellyBellyWikiUtility::setRegistrar(function (JellyBellyWikiUtility $u): void {
    $u->clean = [JellyBellyWikiClean::class, 'call'];
    $u->done = [JellyBellyWikiDone::class, 'call'];
    $u->make_error = [JellyBellyWikiMakeError::class, 'call'];
    $u->feature_add = [JellyBellyWikiFeatureAdd::class, 'call'];
    $u->feature_hook = [JellyBellyWikiFeatureHook::class, 'call'];
    $u->feature_init = [JellyBellyWikiFeatureInit::class, 'call'];
    $u->fetcher = [JellyBellyWikiFetcher::class, 'call'];
    $u->make_fetch_def = [JellyBellyWikiMakeFetchDef::class, 'call'];
    $u->make_context = [JellyBellyWikiMakeContext::class, 'call'];
    $u->make_options = [JellyBellyWikiMakeOptions::class, 'call'];
    $u->make_request = [JellyBellyWikiMakeRequest::class, 'call'];
    $u->make_response = [JellyBellyWikiMakeResponse::class, 'call'];
    $u->make_result = [JellyBellyWikiMakeResult::class, 'call'];
    $u->make_point = [JellyBellyWikiMakePoint::class, 'call'];
    $u->make_spec = [JellyBellyWikiMakeSpec::class, 'call'];
    $u->make_url = [JellyBellyWikiMakeUrl::class, 'call'];
    $u->param = [JellyBellyWikiParam::class, 'call'];
    $u->prepare_auth = [JellyBellyWikiPrepareAuth::class, 'call'];
    $u->prepare_body = [JellyBellyWikiPrepareBody::class, 'call'];
    $u->prepare_headers = [JellyBellyWikiPrepareHeaders::class, 'call'];
    $u->prepare_method = [JellyBellyWikiPrepareMethod::class, 'call'];
    $u->prepare_params = [JellyBellyWikiPrepareParams::class, 'call'];
    $u->prepare_path = [JellyBellyWikiPreparePath::class, 'call'];
    $u->prepare_query = [JellyBellyWikiPrepareQuery::class, 'call'];
    $u->graphql_body = [JellyBellyWikiGraphql::class, 'body'];
    $u->graphql_errors = [JellyBellyWikiGraphql::class, 'errors'];
    $u->result_basic = [JellyBellyWikiResultBasic::class, 'call'];
    $u->result_body = [JellyBellyWikiResultBody::class, 'call'];
    $u->result_headers = [JellyBellyWikiResultHeaders::class, 'call'];
    $u->transform_request = [JellyBellyWikiTransformRequest::class, 'call'];
    $u->transform_response = [JellyBellyWikiTransformResponse::class, 'call'];
});
